name: Reusable - Semgrep & upload SARIF
on:
  workflow_call:
    inputs:
      semgrep_config:
        description: "Chemin ou URL des règles"
        required: false
        default: "p/ci"
        type: string
      exclude:
        description: "Glob patterns à exclure"
        required: false
        default: ""
        type: string
jobs:
  semgrep:
    name: Static Scan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        env:
         SEMGREP_SEND_METRICS: "off"
        with:
         config: ${{ inputs.semgrep_config }}
         generateSarif: true

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
         sarif_file: semgrep.sarif