name: Reusable - Semgrep & upload SARIF
on:
  workflow_call:
    inputs:
      semgrep_config:
        description: "Chemin ou URL des règles"
        required: false
        default: "p/ci"
        type: string
      exclude:
        description: "Glob patterns à exclure"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Static Scan
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [self-hosted, ubuntu-latest, windows-latest, macos-latest] #de ce que jai compris de la consigne, on veut self-hosted ET github

    steps:
      - name: Clean diagnostic logs to avoid conflicts (self-hosted only)
        if: contains(runner.labels, 'self-hosted')
        run: |
          echo "Cleaning old _diag log files on self-hosted runner..."
          find "$RUNNER_TOOL_CACHE/../_diag/pages" -type f -name "*.log" -delete 2>/dev/null || true

      - name: Afficher l'environnement du runner
        run: |
         echo "Runner Name: $RUNNER_NAME"
         echo "OS: $RUNNER_OS"
         echo "Architecture: $RUNNER_ARCH"
         echo "Runner Labels: $RUNNER_LABELS"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        continue-on-error: true
        env:
          SEMGREP_CONFIG: ${{ inputs.semgrep_config }}
        run: |
          semgrep --config "$SEMGREP_CONFIG" --sarif > semgrep.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif