name: Reusable - Semgrep & upload SARIF
on:
  workflow_call:
    inputs:
      semgrep_config:
        description: "Chemin ou URL des règles"
        required: false
        default: "p/ci"
        type: string
      exclude:
        description: "Glob patterns à exclure"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Static Scan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Afficher l'environnement du runner
        run: |
         echo "Runner Name: $RUNNER_NAME"
         echo "OS: $RUNNER_OS"
         echo "Architecture: $RUNNER_ARCH"
         echo "Runner Labels: $RUNNER_LABELS"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: 🔍 Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: ${{ inputs.semgrep_config }}
          generateSarif: true
          upload: false           
          exclude: ${{ inputs.exclude }}

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif